[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
markers =
    asyncio: mark test to run asynchronously using pytest-asyncio

filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::PendingDeprecationWarning
    ignore::FutureWarning
